
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: speak_app_development

  
test:
  <<: *default
  database: speak_app_test


production:
  <<: *default
  database: speak_app_production
  username: speak_app
  password: <%= ENV['SPEAK_APP_DATABASE_PASSWORD'] %>
